CREATE TABLE MNL_ARP_INV_NOTE
( 
    INV_OID NUMBER(19,0), 
    INV_NUM VARCHAR2(30 CHAR), 
    REF_NUM VARCHAR2(20 CHAR), 
    BOUND VARCHAR2(2 CHAR), 
    CUST_NAME VARCHAR2(150 CHAR), 
    STATUS  VARCHAR2(20 CHAR),
    PMT_TTL_AMT  NUMBER(19,2),
    TTL_AMT_VAL  NUMBER(19,2),
    OST_AMT NUMBER(19,2),
    PRIMARY KEY (INV_OID)
); 

CREATE TABLE MNL_ARP_POOL_CHRG
( 
    POOL_ID         NUMBER(19,0),
    CHARGESET_ID         NUMBER(19,0),
    BOUND         VARCHAR2(2 CHAR),
    CHARGE_CDE         VARCHAR2(3 CHAR),
    BASIS         NUMBER(17,6),
    RATE         NUMBER(16,2),
    INV_OID         NUMBER(19,0),
    PRIMARY KEY (POOL_ID)
);

CREATE TABLE MNL_ARP_COST_SUMM
( 
    COST_SUMM_ID NUMBER(19,0),
    INV_NO         NUMBER(19,0),
    TTL_AMT         NUMBER(19,2),
    PAID_TTL_AMT         NUMBER(19,2),
    CHARGE_ID       NUMBER(19,0),
    PRIMARY KEY (COST_SUMM_ID)
);