/*
 * File: app/view/MainViewPort.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainViewPort', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.button.Button'
    ],

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    items: [
                        {
                            xtype: 'form',
                            height: 239,
                            bodyPadding: 10,
                            title: 'Registrayion to Pedro website',
                            items: [
                                {
                                    xtype: 'container',
                                    height: 94,
                                    width: 471,
                                    layout: 'anchor',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            id: 'userTb',
                                            width: 427,
                                            fieldLabel: 'Username'
                                        },
                                        {
                                            xtype: 'textfield',
                                            id: 'pass1tb',
                                            width: 427,
                                            fieldLabel: 'Password'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'button',
                                    id: 'createButton',
                                    text: 'Create Account',
                                    listeners: {
                                        click: {
                                            fn: me.onCreateButtonClick,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onCreateButtonClick: function(button, e, eOpts) {
		var user = Ext.getCmp('userTb').getValue();
		var pass = Ext.getCmp('pass1tb').getValue();
		if(user=="Pedro" && pass =="1234")
		{
			window.location.assign('test1.html');
        Ext.MessageBox.alert("PedroSite","User Accepted");
        console.log(userTb.value);
		}else
			Ext.MessageBox.alert("PedroSite","Invalid inputs");
    }

});