/*
 * File: app/view/MyViewport1.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport1', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.TextArea',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.grid.column.Boolean',
        'Ext.grid.View',
        'Ext.button.Button'
    ],

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 359,
                    width: 548,
                    layout: 'absolute',
                    bodyPadding: 10,
                    title: 'Planet',
                    items: [
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            fieldLabel: 'Enter anything:'
                        },
                        {
                            xtype: 'gridpanel',
                            x: 10,
                            y: 100,
                            width: 520,
                            title: 'List of Planets',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'string',
                                    text: 'Name'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    dataIndex: 'number',
                                    text: 'Weight'
                                },
                                {
                                    xtype: 'datecolumn',
                                    width: 173,
                                    dataIndex: 'date',
                                    text: 'Number of Aliens'
                                },
                                {
                                    xtype: 'booleancolumn',
                                    width: 180,
                                    dataIndex: 'bool',
                                    text: 'Number of Humans'
                                }
                            ]
                        },
                        {
                            xtype: 'button',
                            x: 20,
                            y: 270,
                            height: 30,
                            text: 'Back',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        this.push(Ext.create('MyApp.view.MyViewport',{
                    title:'Test' }));
    }

});