/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.form.Panel',
        'Ext.button.Button',
        'Ext.Img'
    ],

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 361,
                    width: 362,
                    layout: 'absolute',
                    bodyPadding: 10,
                    title: 'Planets',
                    items: [
                        {
                            xtype: 'button',
                            x: 120,
                            y: 240,
                            text: 'Planet Page',
                            tooltip: 'Planet',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'button',
                            x: 140,
                            y: 270,
                            text: 'About',
                            tooltip: 'About me',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick1,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'image',
                            x: 10,
                            y: 10,
                            height: 220,
                            width: 340,
                            src: 'nine-planets.jpg'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        this.push(Ext.create('MyApp.view.MyViewport1',{
                    title:'Test' }));
    },

    onButtonClick1: function(button, e, eOpts) {
        this.push(Ext.create('MyApp.view.MyViewport2',{
                    title:'Test' }));
    }

});