/*
 * File: app/view/MyViewport2.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport2', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.form.Panel',
        'Ext.button.Button',
        'Ext.Img'
    ],

    layout: 'absolute',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    height: 330,
                    width: 420,
                    layout: 'absolute',
                    bodyPadding: 10,
                    title: 'About',
                    items: [
                        {
                            xtype: 'button',
                            x: 20,
                            y: 260,
                            text: 'Back',
                            listeners: {
                                click: {
                                    fn: me.onButtonClick,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'image',
                            x: 10,
                            y: 10,
                            height: 240,
                            width: 400,
                            src: 'th.jpg'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onButtonClick: function(button, e, eOpts) {
        this.push(Ext.create('MyApp.view.MyViewport',{
                    title:'Test' }));
    }

});