/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ExtHomework.controller.MyController', {
    extend: 'Ext.app.Controller',

    onButtonClick: function(button, e, eOpts) {
        console.log('i am click');

        var year = Ext.getCmp("year").value;
        var month = Ext.getCmp("month").value;
        var money = Ext.getCmp("money").value;

        console.log(year);

        var oRecord = Ext.ModelManager.create({
            "year" : year,
            "month" : month,
            "money" : money
            },'ExtHomework.model.moneyModel');

        Ext.getStore('moneyStore').add(oRecord);
        this.getView('#gridMoney').refresh();
    },

    onLaunch: function() {
        this.oTXTYr = this.getView('year');
        this.oTXTmonth = this.getView('month');
        this.oTXTmoney = this.getView('money');
        this.oFormPanel= this.getView('#input');
        this.oSTRName = this.getStore('moneyStore');
        this.oGRIDNames = this.getView('#gridMoney');

    },

    init: function(application) {
        this.control({
            "#addDetails": {
                click: this.onButtonClick
            }
        });
    }

});
