/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ExtHomework.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Text',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.column.Number',
        'Ext.grid.View'
    ],

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    layout: 'auto',
                    bodyPadding: 10,
                    title: 'Input',
                    dockedItems: [
                        {
                            xtype: 'textfield',
                            dock: 'left',
                            id: 'year',
                            itemId: 'year',
                            fieldLabel: 'Year:',
                            name: 'year'
                        },
                        {
                            xtype: 'textfield',
                            dock: 'left',
                            id: 'month',
                            itemId: 'month',
                            fieldLabel: 'Month',
                            name: 'month'
                        },
                        {
                            xtype: 'textfield',
                            dock: 'left',
                            id: 'money',
                            itemId: 'money',
                            fieldLabel: 'Money',
                            name: 'money'
                        },
                        {
                            xtype: 'toolbar',
                            dock: 'bottom',
                            items: [
                                {
                                    xtype: 'tbfill'
                                },
                                {
                                    xtype: 'button',
                                    id: 'addDetails',
                                    itemId: 'addDetails',
                                    text: 'Add'
                                },
                                {
                                    xtype: 'button',
                                    id: 'showChart',
                                    itemId: 'showChart',
                                    text: 'Show Chart'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    title: 'Money Saved',
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'string',
                            text: 'Year'
                        },
                        {
                            xtype: 'gridcolumn',
                            text: 'Month'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'number',
                            text: 'Money'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});