
package com.oocl.barceja2.sw3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculatorCatalogueService", targetNamespace = "http://webservice.escobjo.com/", wsdlLocation = "http://zha-ita006-w7:8080/CalculatorWebService/CalculatorCatalogueService?wsdl")
public class CalculatorCatalogueService
    extends Service
{

    private final static URL CALCULATORCATALOGUESERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATORCATALOGUESERVICE_EXCEPTION;
    private final static QName CALCULATORCATALOGUESERVICE_QNAME = new QName("http://webservice.escobjo.com/", "CalculatorCatalogueService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://zha-ita006-w7:8080/CalculatorWebService/CalculatorCatalogueService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATORCATALOGUESERVICE_WSDL_LOCATION = url;
        CALCULATORCATALOGUESERVICE_EXCEPTION = e;
    }

    public CalculatorCatalogueService() {
        super(__getWsdlLocation(), CALCULATORCATALOGUESERVICE_QNAME);
    }

    public CalculatorCatalogueService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATORCATALOGUESERVICE_QNAME, features);
    }

    public CalculatorCatalogueService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATORCATALOGUESERVICE_QNAME);
    }

    public CalculatorCatalogueService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATORCATALOGUESERVICE_QNAME, features);
    }

    public CalculatorCatalogueService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorCatalogueService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculatorCatalogue
     */
    @WebEndpoint(name = "CalculatorCataloguePort")
    public CalculatorCatalogue getCalculatorCataloguePort() {
        return super.getPort(new QName("http://webservice.escobjo.com/", "CalculatorCataloguePort"), CalculatorCatalogue.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorCatalogue
     */
    @WebEndpoint(name = "CalculatorCataloguePort")
    public CalculatorCatalogue getCalculatorCataloguePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.escobjo.com/", "CalculatorCataloguePort"), CalculatorCatalogue.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATORCATALOGUESERVICE_EXCEPTION!= null) {
            throw CALCULATORCATALOGUESERVICE_EXCEPTION;
        }
        return CALCULATORCATALOGUESERVICE_WSDL_LOCATION;
    }

}
