
package com.oocl.barceja2.sw3;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorCatalogue", targetNamespace = "http://webservice.escobjo.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorCatalogue {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCalculatorOperations", targetNamespace = "http://webservice.escobjo.com/", className = "com.escobjo.webservice.GetCalculatorOperations")
    @ResponseWrapper(localName = "getCalculatorOperationsResponse", targetNamespace = "http://webservice.escobjo.com/", className = "com.escobjo.webservice.GetCalculatorOperationsResponse")
    @Action(input = "http://webservice.escobjo.com/CalculatorCatalogue/getCalculatorOperationsRequest", output = "http://webservice.escobjo.com/CalculatorCatalogue/getCalculatorOperationsResponse")
    public List<String> getCalculatorOperations();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getValuestoCalculate", targetNamespace = "http://webservice.escobjo.com/", className = "com.escobjo.webservice.GetValuestoCalculate")
    @ResponseWrapper(localName = "getValuestoCalculateResponse", targetNamespace = "http://webservice.escobjo.com/", className = "com.escobjo.webservice.GetValuestoCalculateResponse")
    @Action(input = "http://webservice.escobjo.com/CalculatorCatalogue/getValuestoCalculateRequest", output = "http://webservice.escobjo.com/CalculatorCatalogue/getValuestoCalculateResponse")
    public Double getValuestoCalculate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2);

}
