
package com.oocl.allarra.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Services1Service", targetNamespace = "http://soap.allarra.oocl.com/", wsdlLocation = "http://ZHA-ITA055-W7:8080/ALLARRA_22AUG17_SW-0.0.6-SNAPSHOT/Services1Service?wsdl")
public class Services1Service
    extends Service
{

    private final static URL SERVICES1SERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICES1SERVICE_EXCEPTION;
    private final static QName SERVICES1SERVICE_QNAME = new QName("http://soap.allarra.oocl.com/", "Services1Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ZHA-ITA055-W7:8080/ALLARRA_22AUG17_SW-0.0.6-SNAPSHOT/Services1Service?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICES1SERVICE_WSDL_LOCATION = url;
        SERVICES1SERVICE_EXCEPTION = e;
    }

    public Services1Service() {
        super(__getWsdlLocation(), SERVICES1SERVICE_QNAME);
    }

    public Services1Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICES1SERVICE_QNAME, features);
    }

    public Services1Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICES1SERVICE_QNAME);
    }

    public Services1Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICES1SERVICE_QNAME, features);
    }

    public Services1Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Services1Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Services1
     */
    @WebEndpoint(name = "Services1Port")
    public Services1 getServices1Port() {
        return super.getPort(new QName("http://soap.allarra.oocl.com/", "Services1Port"), Services1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Services1
     */
    @WebEndpoint(name = "Services1Port")
    public Services1 getServices1Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.allarra.oocl.com/", "Services1Port"), Services1.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICES1SERVICE_EXCEPTION!= null) {
            throw SERVICES1SERVICE_EXCEPTION;
        }
        return SERVICES1SERVICE_WSDL_LOCATION;
    }

}
