
package com.oocl.allarra.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicesService", targetNamespace = "http://soap.allarra.oocl.com/", wsdlLocation = "http://ZHA-ITA055-W7:8080/ALLARRA_22AUG17_SW-0.0.6-SNAPSHOT/ServicesService?wsdl")
public class ServicesService
    extends Service
{

    private final static URL SERVICESSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICESSERVICE_EXCEPTION;
    private final static QName SERVICESSERVICE_QNAME = new QName("http://soap.allarra.oocl.com/", "ServicesService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ZHA-ITA055-W7:8080/ALLARRA_22AUG17_SW-0.0.6-SNAPSHOT/ServicesService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICESSERVICE_WSDL_LOCATION = url;
        SERVICESSERVICE_EXCEPTION = e;
    }

    public ServicesService() {
        super(__getWsdlLocation(), SERVICESSERVICE_QNAME);
    }

    public ServicesService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICESSERVICE_QNAME, features);
    }

    public ServicesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICESSERVICE_QNAME);
    }

    public ServicesService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICESSERVICE_QNAME, features);
    }

    public ServicesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicesService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Services
     */
    @WebEndpoint(name = "ServicesPort")
    public Services getServicesPort() {
        return super.getPort(new QName("http://soap.allarra.oocl.com/", "ServicesPort"), Services.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Services
     */
    @WebEndpoint(name = "ServicesPort")
    public Services getServicesPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.allarra.oocl.com/", "ServicesPort"), Services.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICESSERVICE_EXCEPTION!= null) {
            throw SERVICESSERVICE_EXCEPTION;
        }
        return SERVICESSERVICE_WSDL_LOCATION;
    }

}
