
package com.oocl.allarra.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Services", targetNamespace = "http://soap.allarra.oocl.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Services {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductCategories", targetNamespace = "http://soap.allarra.oocl.com/", className = "com.oocl.allarra.soap.GetProductCategories")
    @ResponseWrapper(localName = "getProductCategoriesResponse", targetNamespace = "http://soap.allarra.oocl.com/", className = "com.oocl.allarra.soap.GetProductCategoriesResponse")
    @Action(input = "http://soap.allarra.oocl.com/Services/getProductCategoriesRequest", output = "http://soap.allarra.oocl.com/Services/getProductCategoriesResponse")
    public List<String> getProductCategories();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.oocl.allarra.soap.ProductClass
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSnackProperty", targetNamespace = "http://soap.allarra.oocl.com/", className = "com.oocl.allarra.soap.GetSnackProperty")
    @ResponseWrapper(localName = "getSnackPropertyResponse", targetNamespace = "http://soap.allarra.oocl.com/", className = "com.oocl.allarra.soap.GetSnackPropertyResponse")
    @Action(input = "http://soap.allarra.oocl.com/Services/getSnackPropertyRequest", output = "http://soap.allarra.oocl.com/Services/getSnackPropertyResponse")
    public ProductClass getSnackProperty(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.oocl.allarra.soap.ProductClass>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSnacksAvailability", targetNamespace = "http://soap.allarra.oocl.com/", className = "com.oocl.allarra.soap.GetSnacksAvailability")
    @ResponseWrapper(localName = "getSnacksAvailabilityResponse", targetNamespace = "http://soap.allarra.oocl.com/", className = "com.oocl.allarra.soap.GetSnacksAvailabilityResponse")
    @Action(input = "http://soap.allarra.oocl.com/Services/getSnacksAvailabilityRequest", output = "http://soap.allarra.oocl.com/Services/getSnacksAvailabilityResponse")
    public List<ProductClass> getSnacksAvailability();

}
