
package com.forrest.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductCatalogue", targetNamespace = "http://webservice.forrest.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductCatalogue {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProductCategories", targetNamespace = "http://webservice.forrest.com/", className = "com.forrest.webservice.GetProductCategories")
    @ResponseWrapper(localName = "getProductCategoriesResponse", targetNamespace = "http://webservice.forrest.com/", className = "com.forrest.webservice.GetProductCategoriesResponse")
    @Action(input = "http://webservice.forrest.com/ProductCatalogue/getProductCategoriesRequest", output = "http://webservice.forrest.com/ProductCatalogue/getProductCategoriesResponse")
    public List<String> getProductCategories();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "gegProducts", targetNamespace = "http://webservice.forrest.com/", className = "com.forrest.webservice.GegProducts")
    @ResponseWrapper(localName = "gegProductsResponse", targetNamespace = "http://webservice.forrest.com/", className = "com.forrest.webservice.GegProductsResponse")
    @Action(input = "http://webservice.forrest.com/ProductCatalogue/gegProductsRequest", output = "http://webservice.forrest.com/ProductCatalogue/gegProductsResponse")
    public List<String> gegProducts(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
