
package com.forrest.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProductCatalogueService", targetNamespace = "http://webservice.forrest.com/", wsdlLocation = "http://zha-ita024-w7:8080/MyWebService/ProductCatalogueService?wsdl")
public class ProductCatalogueService
    extends Service
{

    private final static URL PRODUCTCATALOGUESERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTCATALOGUESERVICE_EXCEPTION;
    private final static QName PRODUCTCATALOGUESERVICE_QNAME = new QName("http://webservice.forrest.com/", "ProductCatalogueService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://zha-ita024-w7:8080/MyWebService/ProductCatalogueService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTCATALOGUESERVICE_WSDL_LOCATION = url;
        PRODUCTCATALOGUESERVICE_EXCEPTION = e;
    }

    public ProductCatalogueService() {
        super(__getWsdlLocation(), PRODUCTCATALOGUESERVICE_QNAME);
    }

    public ProductCatalogueService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTCATALOGUESERVICE_QNAME, features);
    }

    public ProductCatalogueService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTCATALOGUESERVICE_QNAME);
    }

    public ProductCatalogueService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTCATALOGUESERVICE_QNAME, features);
    }

    public ProductCatalogueService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductCatalogueService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductCatalogue
     */
    @WebEndpoint(name = "ProductCataloguePort")
    public ProductCatalogue getProductCataloguePort() {
        return super.getPort(new QName("http://webservice.forrest.com/", "ProductCataloguePort"), ProductCatalogue.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductCatalogue
     */
    @WebEndpoint(name = "ProductCataloguePort")
    public ProductCatalogue getProductCataloguePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.forrest.com/", "ProductCataloguePort"), ProductCatalogue.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTCATALOGUESERVICE_EXCEPTION!= null) {
            throw PRODUCTCATALOGUESERVICE_EXCEPTION;
        }
        return PRODUCTCATALOGUESERVICE_WSDL_LOCATION;
    }

}
