/*
 * File: app/store/Records.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TestApp.store.Records', {
    extend: 'Ext.data.Store',

    requires: [
        'TestApp.model.Record',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'TestApp.model.Record',
            storeId: 'MyStore',
            data: [
                {
                    id: 1,
                    title: 'OG',
                    description: 'Frankfurt champion',
                    date: '10/1/2010',
                    isFeatured: true
                },
                {
                    id: 2,
                    title: 'Navi',
                    description: 'European Team',
                    date: '10/2/2010',
                    isFeatured: false
                },
                {
                    id: 3,
                    title: 'TNC',
                    description: 'Filipino Team',
                    date: '10/3/2010',
                    isFeatured: false
                },
                {
                    id: 4,
                    title: 'Team Liquid',
                    description: 'Chinese Team',
                    date: '10/4/2010',
                    isFeatured: true
                },
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});