/*
 * File: app/view/MyImg.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyImg', {
    extend: 'Ext.Img',

    draggable: true,
    height: 201,
    width: 201,
    src: 'C:%5CUsers%5Ctengkh%5CDesktop%5CdragAndDrop%5Capp%5Cview%5Cblack.jpeg',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});