/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'Ext.Img'
    ],

    layout: 'absolute',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'image',
                    x: 250,
                    y: 70,
                    draggable: true,
                    height: 290,
                    width: 201,
                    src: 'app/img/2.jpg'
                },
                {
                    xtype: 'image',
                    x: 250,
                    y: 70,
                    draggable: true,
                    height: 290,
                    width: 201,
                    src: 'app/img/1.jpg'
                },
                {
                    xtype: 'image',
                    x: 250,
                    y: 70,
                    draggable: true,
                    height: 290,
                    width: 201,
                    src: 'app/img/3.jpg'
                },
                {
                    xtype: 'image',
                    x: 250,
                    y: 70,
                    draggable: true,
                    height: 290,
                    width: 201,
                    src: 'app/img/4.jpg'
                },
                {
                    xtype: 'image',
                    x: 250,
                    y: 70,
                    draggable: true,
                    height: 290,
                    width: 201,
                    src: 'app/img/5.jpg'
                },
                {
                    xtype: 'image',
                    x: 250,
                    y: 70,
                    draggable: true,
                    height: 290,
                    width: 201,
                    src: 'app/img/6.jpg'
                }
            ]
        });

        me.callParent(arguments);
    }

});