
package com.calculator.webservice1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorWSExecute", targetNamespace = "http://webservice1.calculator.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorWSExecute {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "multiply", targetNamespace = "http://webservice1.calculator.com/", className = "com.calculator.webservice1.Multiply")
    @ResponseWrapper(localName = "multiplyResponse", targetNamespace = "http://webservice1.calculator.com/", className = "com.calculator.webservice1.MultiplyResponse")
    @Action(input = "http://webservice1.calculator.com/CalculatorWSExecute/multiplyRequest", output = "http://webservice1.calculator.com/CalculatorWSExecute/multiplyResponse")
    public String multiply(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addition", targetNamespace = "http://webservice1.calculator.com/", className = "com.calculator.webservice1.Addition")
    @ResponseWrapper(localName = "additionResponse", targetNamespace = "http://webservice1.calculator.com/", className = "com.calculator.webservice1.AdditionResponse")
    @Action(input = "http://webservice1.calculator.com/CalculatorWSExecute/additionRequest", output = "http://webservice1.calculator.com/CalculatorWSExecute/additionResponse")
    public String addition(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtraction", targetNamespace = "http://webservice1.calculator.com/", className = "com.calculator.webservice1.Subtraction")
    @ResponseWrapper(localName = "subtractionResponse", targetNamespace = "http://webservice1.calculator.com/", className = "com.calculator.webservice1.SubtractionResponse")
    @Action(input = "http://webservice1.calculator.com/CalculatorWSExecute/subtractionRequest", output = "http://webservice1.calculator.com/CalculatorWSExecute/subtractionResponse")
    public String subtraction(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "squareRoot", targetNamespace = "http://webservice1.calculator.com/", className = "com.calculator.webservice1.SquareRoot")
    @ResponseWrapper(localName = "squareRootResponse", targetNamespace = "http://webservice1.calculator.com/", className = "com.calculator.webservice1.SquareRootResponse")
    @Action(input = "http://webservice1.calculator.com/CalculatorWSExecute/squareRootRequest", output = "http://webservice1.calculator.com/CalculatorWSExecute/squareRootResponse")
    public String squareRoot(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

}
