
package com.calculator.webservice1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculatorWSExecuteService", targetNamespace = "http://webservice1.calculator.com/", wsdlLocation = "http://ZHA-ITA107-W7:8080/CalcWS/CalculatorWSExecuteService?wsdl")
public class CalculatorWSExecuteService
    extends Service
{

    private final static URL CALCULATORWSEXECUTESERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULATORWSEXECUTESERVICE_EXCEPTION;
    private final static QName CALCULATORWSEXECUTESERVICE_QNAME = new QName("http://webservice1.calculator.com/", "CalculatorWSExecuteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ZHA-ITA107-W7:8080/CalcWS/CalculatorWSExecuteService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATORWSEXECUTESERVICE_WSDL_LOCATION = url;
        CALCULATORWSEXECUTESERVICE_EXCEPTION = e;
    }

    public CalculatorWSExecuteService() {
        super(__getWsdlLocation(), CALCULATORWSEXECUTESERVICE_QNAME);
    }

    public CalculatorWSExecuteService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATORWSEXECUTESERVICE_QNAME, features);
    }

    public CalculatorWSExecuteService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATORWSEXECUTESERVICE_QNAME);
    }

    public CalculatorWSExecuteService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATORWSEXECUTESERVICE_QNAME, features);
    }

    public CalculatorWSExecuteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorWSExecuteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculatorWSExecute
     */
    @WebEndpoint(name = "CalculatorWSExecutePort")
    public CalculatorWSExecute getCalculatorWSExecutePort() {
        return super.getPort(new QName("http://webservice1.calculator.com/", "CalculatorWSExecutePort"), CalculatorWSExecute.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorWSExecute
     */
    @WebEndpoint(name = "CalculatorWSExecutePort")
    public CalculatorWSExecute getCalculatorWSExecutePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice1.calculator.com/", "CalculatorWSExecutePort"), CalculatorWSExecute.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATORWSEXECUTESERVICE_EXCEPTION!= null) {
            throw CALCULATORWSEXECUTESERVICE_EXCEPTION;
        }
        return CALCULATORWSEXECUTESERVICE_WSDL_LOCATION;
    }

}
