
package com.oocl.bangipr.sw1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Calculator", targetNamespace = "http://sw1.bangipr.oocl.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Calculator {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "Division")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Division", targetNamespace = "http://sw1.bangipr.oocl.com/", className = "com.oocl.bangipr.sw1.Division")
    @ResponseWrapper(localName = "DivisionResponse", targetNamespace = "http://sw1.bangipr.oocl.com/", className = "com.oocl.bangipr.sw1.DivisionResponse")
    @Action(input = "http://sw1.bangipr.oocl.com/Calculator/DivisionRequest", output = "http://sw1.bangipr.oocl.com/Calculator/DivisionResponse")
    public Double division(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "Addition")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Addition", targetNamespace = "http://sw1.bangipr.oocl.com/", className = "com.oocl.bangipr.sw1.Addition")
    @ResponseWrapper(localName = "AdditionResponse", targetNamespace = "http://sw1.bangipr.oocl.com/", className = "com.oocl.bangipr.sw1.AdditionResponse")
    @Action(input = "http://sw1.bangipr.oocl.com/Calculator/AdditionRequest", output = "http://sw1.bangipr.oocl.com/Calculator/AdditionResponse")
    public Double addition(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "Subtraction")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Subtraction", targetNamespace = "http://sw1.bangipr.oocl.com/", className = "com.oocl.bangipr.sw1.Subtraction")
    @ResponseWrapper(localName = "SubtractionResponse", targetNamespace = "http://sw1.bangipr.oocl.com/", className = "com.oocl.bangipr.sw1.SubtractionResponse")
    @Action(input = "http://sw1.bangipr.oocl.com/Calculator/SubtractionRequest", output = "http://sw1.bangipr.oocl.com/Calculator/SubtractionResponse")
    public Double subtraction(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Double
     */
    @WebMethod(operationName = "Multiplication")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Multiplication", targetNamespace = "http://sw1.bangipr.oocl.com/", className = "com.oocl.bangipr.sw1.Multiplication")
    @ResponseWrapper(localName = "MultiplicationResponse", targetNamespace = "http://sw1.bangipr.oocl.com/", className = "com.oocl.bangipr.sw1.MultiplicationResponse")
    @Action(input = "http://sw1.bangipr.oocl.com/Calculator/MultiplicationRequest", output = "http://sw1.bangipr.oocl.com/Calculator/MultiplicationResponse")
    public Double multiplication(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
